# config.yml

backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
local_backend: 
  url: http://localhost:8082/api/v1
media_folder: 'assets/uploads'
logo_url: 'https://cdn.shopify.com/s/files/1/1375/4313/files/atlas-logo-simple.png?v=1480492227'
publish_mode: editorial_workflow
collections:
  - name: "home"
    label: "Home Page Content Sections"
    files: 
      - label: "Top Hero Image"
        name: "hero_image"
        file: "_data/hero_image.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "hero_image" }
          - { label: "Hero Image", name: hero_image, widget: image, hint: "Hero Image Background"}
          - { label: "Hero Image Alt Text", name: hero_image_alt, widget: string, hint: "Hero Image Alt Text" }
      - label: "More To The Mix"
        name: "more_to_the_mix"
        file: "_data/more_to_the_mix.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "more_to_the_mix" }
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Long text", name: "body", widget: "text"}
      - label: "Hang Your Hats Here"
        name: "hang_your_hats_here"
        file: "_data/hang_your_hats_here.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "hang_your_hats_here" }
      - label: "life_with_benefits"
        name: "life_with_benefits"
        file: "_data/life_with_benefits.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "life_with_benefits" }
      - label: "Corner Rendering / Image Row "
        name: "corner_renderings"
        file: "_data/corner_renderings.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "corner_renderings" }
          - { label: "Corner Rendering / Image", name: corner_rendering, widget: image, hint: "Corner Rendering Image"}
      - label: "businesses_welcome"
        name: "businesses_welcome"
        file: "_data/businesses_welcome.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "businesses_welcome" }
      - label: "the_intersection"
        name: "the_intersection"
        file: "_data/the_intersection.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "the_intersection" }
          - { label: "Title", name: "title", widget: "string"}
          - { label: "Long text", name: "body", widget: "text"}
      - label: "destined_for_destionation"
        name: "destined_for_destionation"
        file: "_data/destined_for_destionation.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "destined_for_destionation" }
      - label: "Site Rendering / Image Row "
        name: "site_renderings"
        file: "_data/site_renderings.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "site_renderings" }
          - { label: "Site Rendering / Image", name: site_rendering, widget: image, hint: "Site Rendering Image"}
      - label: "The People Behind The Place"
        name: "the_people_behind"
        file: "_data/the_people_behind.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "the_people_behind" }
          - { label: "Column 1 Title", name: "c1t", widget: "string"}
          - { label: "Column 1 Description", name: "c1d", widget: "text"}
          - { label: "Column 1 Link", name: "c1", widget: "string"}
          - { label: "Column 2 Title", name: "c2t", widget: "string"}
          - { label: "Column 2 Description", name: "c2d", widget: "text"}
          - { label: "Column 2 Link", name: "c2l", widget: "string"}
          - { label: "Column 3 Title", name: "c3t", widget: "string"}
          - { label: "Column 3 Description", name: "c3d", widget: "text"}
          - { label: "Column 3 Link", name: "c3l", widget: "string"}
          - { label: "Column 4 Title", name: "c4t", widget: "string"}
          - { label: "Column 4 Description", name: "c4d", widget: "text"}
          - { label: "Column 4 Link", name: "c4l", widget: "string"}

      - label: "now_happening"
        name: "now_happening"
        file: "_data/now_happening.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "now_happening" }
      - label: "interest_list"
        name: "interest_list"
        file: "_data/interest_list.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "interest_list" }
      - label: "footer_hero"
        name: "footer_hero"
        file: "_data/footer_hero.yml"
        fields:
          - { label: name, name: name, widget: string, hint: "footer_hero" }
  - name: "global"
    label: "Global"
    files:
      - label: "Business Info"
        name: "info"
        file: "_data/business.yml"
        fields:
          - {label: name, name: name, widget: string}
          - {label: address_full, name: address_full, widget: string, hint: "Example: 333 S. Franklin Street Tampa, FL 33602"}
          - {label: address_street, name: address_street, widget: string, hint: "Example: 333 S. Franklin Street"}
          - {label: address_city, name: address_city, widget: string, hint: "Tampa"}
          - {label: phone_primay, name: phone_primay, widget: string, pattern: ['[(]?\d{3}[-.)]?[ ]?\d{3}[-.]?\d{4}\b', "Must be a phone number"], hint: "(813) 123-4567"}
          - {label: phone_secondary, name: phone_secondary, widget: string, hint: "(813) 765-4321"}
          - {label: fax, name: fax, widget: string, hint: "(813) 666-6666"}
          - {label: email_primary, name: email_primary, widget: string, pattern: ['([\w\.\-_]+)?\w+@[\w-_]+(\.\w+){1,}', "Must be an email address"]}
          - {label: "Legal Text", name: legal_text, widget: string, hint: "Legal text at the bottom of the site"}
          - {label: "Legal Image", name: legal_image, widget: image, hint: "EHO image by legal footer"}
      - label: "Social Media"
        name: "social"
        file: "_data/social_media.yml"
        fields:
          - label: platform
            name: platform
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Icon, name: icon, widget: string}
              - {label: Link, name: link, widget: string}
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Author', name: 'author', widget: 'text' }
      - { label: 'Hero', name: 'hero', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'pages'
    label: 'Pages'
    editor:
      preview: false
    files:
      - label: 'About Page'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'hidden', default: 'about' }
          - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'about' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
